### ISSUE TITLE
소스코드 사용 가능한지 궁금합니다.

### ISSUE THREAD

**Issue by norhu1130** [KKuTuDotNet/KKuTu#2]
안녕하세요.
워터끄투 대표 norhu1130입니다.
먼저 KKuTuDotNet의 무궁한 성장을 기원합니다.
in_portal.js (65줄 부터 95줄까지)
in_portal.css (전체)
portal.pug(27줄부터 38줄까지 일부수정)
위 파일에대한 소스코드를 사용하고자 합니다.
사용했다는 안내는 남길예정이며 사용가능한지 여쭈어보려고합니다.
감사합니다.

**Comment by kdhkr** [comment]
끄투닷넷의 소스 코드는 [GNU Affero General Public License v3.0](https://github.com/KKuTuDotNet/KKuTu/blob/production/LICENSE) 라이선스로 배포되고 있습니다.
해당 라이선스의 요구 사항만 충족시킬 경우 소스 코드를 사용하셔도 문제가 없습니다.
